config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  
  resources :posts do
    resources :comments, only: [:create]
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  content    :text
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :content, presence: true
  validates :content, length: { minimum: 250 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :comments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    self.email.split('@')[0].capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def private_access
        redirect_to user_session_path unless signed_in?        
    end

    def is_user?
        @post = Post.find(params[:id])    
        unless current_user.id == @post.user_id    
          flash[:alert] = "Usuario no tienes permisos."
    
          redirect_to posts_path    
        end    
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @post.comments.create(comments_params)
    end

    
    private

    def comments_params
        params.require(:comment).permit(:content).merge(user: current_user)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :private_access, except: [:index, :show]
  before_action :is_user?, except: [:index, :show, :new, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 4).order('created_at DESC')
  end

  def new
    @post = Post.new
    @post.user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user =  current_user
    if @post.save
      flash[:notice] = "Post creado correctamente"
      redirect_to root_path
    else
      render :new
    end
  end

  def show

  end

  def edit
    
  end

  
  def update    
    
    if @post.update(post_params)
      flash[:notice] = "Post actualizado correctamente"
      redirect_to root_path
    else
      render :edit
    end
    
  end

  def destroy
    post.destroy
    flash[:notice] = "Post eliminado correctamente"

    redirect_to root_path    
  end



  
  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :image, :content)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def markdown(text)
        options = {
          filter_html:     true,
          hard_wrap:       true,
          link_attributes: { rel: 'nofollow', target: "_blank" },
          space_after_headers: true,
          fenced_code_blocks: true
        }
    
        extensions = {
          autolink:           true,
          superscript:        true,
          disable_indented_code_blocks: true
        }
    
        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)
    
        markdown.render(text).html_safe
    end

    def gravatar_url(email, size)
      gravatar_id = Digest::MD5::hexdigest(email).downcase  
      default_url = "http://mysite.com/myavatar.png" # Acá puedo poner una ruta para una imagen propia.  
      default_url = "retro"  
      url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI::escape(default_url)}"  
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JBSuperblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>    
    
    <!-- show alerts -->
    <div class="alerts text-center">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <!-- show alerts -->


    
    <%= yield %>


  
  
    <!-- Footer -->
  <footer class="footer footer-light bg-light p-3">
    <a href="https://twitter.com/BerttyJulio" target="_blank"><span class="fa fa-twitter fa-2x"></span></a>
    <a href="https://www.instagram.com/jbcoolness" target="_blank"><span class="fa fa-instagram fa-2x"></span></a>
    <a href="https://github.com/jbcoolness" ><span class="fa fa-github fa-2x"></span></a>          
    <br>
    © 2019 <strong>Julio Bertty</strong>, Todos los Derechos Reservados
  </footer>
  <!-- Footer -->
    

  <!-- hide alerts -->
  <script>
    $(".alert").fadeIn(500).css("opacity", "0.85").delay(6000).slideUp(1000);
    $(".alerts").on('click', '.alert', function(){ $(this).remove() });
  </script>
  <!-- hide alerts -->
  
  </body>
</html>

app/views/posts/_form.html.erb
<header>
    <%= render 'posts/navbar' %>
</header>
<div class="container pt-5">
  <div class="row">
    <div class="col">
      
      <h1><%= @post.new_record? ? "Nuevo Post" : "Editar Post" %></h1>
      <div class="col-sm-5">
        <% if @post.errors.any? %>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li class="list-group-item list-group-item-danger"> <%= message %> </li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <%= form_for @post do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: 'form-control form-control-lg', placeholder: "Titulo del post" %>
        </div>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control form-control-lg', rows: 10, placeholder: "Contenido del post" %>
        </div>
        <div class="form-group">
          <%= f.text_field :image, class: 'form-control form-control-lg', placeholder: "URL de la imagen para el post" %>
        </div>
        <div class="action">
          <%= f.submit @post.new_record? ? "Crear Post" : "Editar Post", class: "btn btn-primary btn-lg" %>
          <%= link_to  "Volver", root_path, class: "btn btn-link" %>
        </div>
      <% end %>
    
    </div>
  </div>
</div>

app/views/posts/_navbar-home.html.erb
<div class="home-wapper">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
      <img src=" <%= image_path('jb-logo-4.png') %>" width="40" height="40" class="d-inline-block align-top" alt="">
      <span> SuperBlog </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= image_tag gravatar_url(current_user.email , 40), class: "rounded-circle" %></li>
          <li class="nav-item dropdown mr-3">            
            <h6 class="nav-link dropdown-toggle mr-4" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hola <%= current_user.username %>!
            </h6>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Nuevo Post", new_post_path, class: "dropdown-item" %>
                <%= link_to "Editar cuenta", edit_user_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>          
        <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar", user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="cita">
      <blockquote class="blockquote fixed-bottom"></blockquote>
        <p>“Da tu primer paso con fe, no es necesario que veas la escalera completa, solo da tu primer paso”</p>
        <cite title="Source Title">Martin Luther King</cite>
      </blockquote>
    </div>
</div>  

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">
      <img src=" <%= image_path('jb-logo-4.png') %>" width="40" height="40" class="d-inline-block align-top" alt="">
        SuperBlog
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li><%= image_tag gravatar_url(current_user.email , 40), class: "rounded-circle" %></li>
        <li class="nav-item dropdown mr-3">
            <h6 class="nav-link dropdown-toggle mr-4" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hola <%= current_user.username %>!
            </h6>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Nuevo Post", new_post_path, class: "dropdown-item" %>
                <%= link_to "Editar cuenta", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>          
          <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar", user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
</nav>

app/views/posts/edit.html.erb
<%= render  "form" %>

app/views/posts/index.html.erb
<header>
    <%= render 'posts/navbar-home' %>
</header>
<div class="container pt-5">
    <div class="row">
        <div class="col-xl">
            <% @posts.each do |post| %>
            <div class="card mb-3">
                <div class="row no-gutters justify-content-center align-items-center">
                  <div class="col-md-3">
                    <img src="<%= post.image %>" class="card-img p-1" alt="...">
                  </div>
                  <div class="col-md-9">
                    <div class="card-body">
                      <h2 class="card-title"> <%= post.title %> </h2>                      
                      <p class="card-text"><small class="text-muted"> Creado <%= post.created_at.strftime("%B %d, %Y") %> Por: <%= post.user.email %> </small></p>
                      <p class="card-text">
                        <%if post.content.length > 250 %> 
                          <%= truncate(post.content, length: 250) %>
                            <%= link_to  "Leer mas...", post, class: "btn btn-outline-primary btn-sm" %>
                          <% else %>
                            <%= post.content %>                          
                        <% end %>
                        <% if user_signed_in? %>
                            <% if current_user.id == post.user_id %>
                                <%= link_to  "Editar", edit_post_path(post), class: "btn btn-outline-secondary btn-sm" %>
                                <%= link_to  "Eliminar", post, method: :delete, data: { confirm: '¿Está seguro que desea eliminar el post?' }, class: "btn btn-outline-danger btn-sm" %>
                            <% end %>                          
                        <% end %>                        
                      </p>                      
                    </div>
                  </div>
                </div>
              </div>

            <% end %>
            
            <% if will_paginate @posts %>
              <div class="row align-items-center">
                <div class="col-md-4"></div>
              <div class="apple_pagination col-sm-4 align-self-center">
                  <%= will_paginate @posts, :container => false %>
              </div>
              <div class="col-md-4"></div>
              </div>
            <% end %>

        </div>
    </div>
</div>

app/views/posts/new.html.erb
<%= render 'form'%>

app/views/posts/show.html.erb
<header>
    <%= render 'posts/navbar' %>
</header>
<div class="container pt-5">
    <div class="row">
        <div class="col body-show">
            <h1 class="text-center"> <%= @post.title %> </h1>            
            <img src="<%= @post.image %>" class="img-show img-fluid img-thumbnail rounded mx-auto d-block m-3" alt="Responsive image">
            <footer class="blockquote-footer text-center mb-3">Publicado: <%= @post.updated_at.to_formatted_s(:long) %>, por <cite title="Source Title"> <%= @post.user.username %> </cite></footer>

            <p class="p-show mt-3 mb-5"> <%= @post.content %> </p>

            <div class="comments pb-5">
                <h4>Comentarios</h4>

                <% @post.comments.each do |comment| %>
                    <div class="card mb-3">
                        <div class="card-header">
                            Usuario: <%= comment.user.username %>
                        </div>
                        <div class="card-body">
                            <blockquote class="blockquote mb-0">
                                <p class="p-comment"> <%= markdown(comment.content) %> </p> 
                            </blockquote>
                        </div>
                    </div>
                <% end %>

                
    
                <% if user_signed_in? %>
                    <%= form_for [@post, @post.comments.build] do |f| %>    
                        <div class="form-group">
                            <%= f.text_area :content, class: "form-control", id:"contentComment", placeholder: "Escriba su comentario (soporta Markdown)" %>
                        </div>                        
                        <div class="action">
                            <%= f.submit "Comentar", class: "btn btn-primary btn-lg" %>
                            <%= link_to  "Volver", root_path, class: "btn btn-link" %>
                        </div>                 
                    <% end %>
                <% else %>
                    <div>
                        <%= link_to  "Volver", root_path, class: "btn btn-link" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>